branches:
  only:
    - 'master'

language: ruby

rvm:
  - 2.3.0

# uncomment this line if user rspec instead of minitest:
# script: bundle exec rspec spec

script:
  - bundle exec rake db:setup
  # - bundle exec rake db: migrate
  - bundle exec rake test